version: 2

models:
  - name: stg_whale_transactions
    columns:
      - name: tx_hash
        tests:
          - unique
          - not_null
      - name: value_eth
        tests:
          - not_null
      - name: whale_tier
        tests:
          - not_null
          - accepted_values:
              values: ['🐋 mega_whale', '🐬 dolphin', '🐟 fish']
